### ISSUE TITLE
upload-flower.py error Invalid type for variable 'tasks'

### ISSUE THREAD

**Issue by black0340** [cvat-ai/blog#3]
python upload-flowers.py
Downloading dataset... done
Unpacking dataset... done
Creating project...
Traceback (most recent call last):
  File "upload-flowers.py", line 164, in <module>
    main()
  File "upload-flowers.py", line 160, in main
    create_tasks(ds_root, client, args.fraction)
  File "upload-flowers.py", line 48, in create_tasks
    project = client.projects.create(
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\core\proxies\model_proxy.py", line 128, in create
    (model, _) = self.api.create(spec)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\api\projects_api.py", line 1380, in create
    return self.create_endpoint.call_with_http_info(**kwargs)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\api_client.py", line 1052, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\api_client.py", line 495, in call_api
    return self.__call_api(**params)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\api_client.py", line 280, in __call_api
    return_data = self.deserialize(
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\api_client.py", line 387, in deserialize
    deserialized_data = validate_and_convert_types(
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1590, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1479, in attempt_convert_item
    raise conversion_exc
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1470, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1384, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 51, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 379, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 51, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model\project_read.py", line 416, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 197, in __setattr__
    self[attr] = value
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 518, in __setitem__
    self.set_attribute(name, value)
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 169, in set_attribute
    value = validate_and_convert_types(
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1590, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "C:\Users\black\AppData\Local\Programs\Python\Python38\lib\site-packages\cvat_sdk\api_client\model_utils.py", line 1465, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
cvat_sdk.api_client.exceptions.ApiTypeError: Invalid type for variable 'tasks'. Required value type is list and passed type was str at ['received_data']['tasks']

what is wrong?? 
i just follow "https://cvat.webflow.io/post/cvat-sdk-pytorch-adapter"

**Comment by SpecLad** [comment]
@black0340 Are you using app.cvat.ai or a different instance of CVAT? I can't reproduce this problem on app.cvat.ai.

**Comment by black0340** [comment]
> @black0340 Are you using app.cvat.ai or a different instance of CVAT? I can't reproduce this problem on app.cvat.ai.

@SpecLad  Thank you for your response

I cloned cvat and used docker-compose up -d

and CVAT_HOST="localhost:8080"

**Comment by SpecLad** [comment]
I see. We recently made a few API changes in the `develop` branch, so the release version of the SDK doesn't work with it. I would advise to run the 2.3.0 release instead.

**Comment by black0340** [comment]
it's working thx!
<img width="329" alt="image" src="https://user-images.githubusercontent.com/57620163/220017410-5183e527-ceeb-488d-8fdd-c77b01168f27.png">
